baseURL = "https://lemmebee.github.io/whoami/"
languageCode = "en-us"
title = "whoami"
theme = "nostyleplease"

[params]
  author = "Ehab ELFEKI"
  
  [params.theme_config]
    appearance = "dark" # valid options: light, dark, auto
    back_home_text = "‚Üê home"
    date_format = "2006-01-02"
    show_description = true
